---
- hosts: data
  vars_prompt:
    - name: "mysql_password"
      prompt: "Mysql Pass"
    - name: "redis_password"
      prompt: "Redis Pass"

  tasks:
  - name: Add MariaDB repository
    apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/ubuntu trusty main' state=present

  - name: Add repository key to the system
    apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

  - name: Install MariaDB Server
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
     - mariadb-server
     - python-mysqldb

  - name: Install Redis Server
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
     - redis-server
     - python-redis

  - name: Create MySQL User
    mysql_user: name=pn priv=parkitectnexus.*:ALL password={{ mysql_password }} state=present

  - name: Create MySQL DB
    mysql_db: name=parkitectnexus state=present

  - name: Setup MySQL bind address
    template: src=conf/data/my.conf dest=/etc/mysql/my.cnf
    notify:
      - restart mariadb

  - name: Update MySQL passes
    mysql_user: 
      name: pn
      host: "{{ item }}" 
      password: "{{ mysql_password }}"
      login_user: on
      login_password: "{{ mysql_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
      - "{{ groups['web'] }}"
      - "{{ groups['worker'] }}"
    notify:
      restart mariadb

  - name: Setup Redis bind address
    lineinfile: dest=/etc/redis/redis.conf regexp='^(.*)bind' line="bind 0.0.0.0" state=present
    notify:
      restart redis

  - name: Setup Redis password
    lineinfile: dest=/etc/redis/redis.conf regexp='^(.*)requirepass' line="requirepass {{ redis_password }}" state=present
    notify:
      restart redis

  handlers:
    - name: restart redis
      service: name=redis-server state=restarted

    - name: restart mariadb
      service: name=mysql state=restarted
