- hosts: worker
  tasks:
  - name: Install nginx
    apt: name=nginx state=latest update_cache=yes

  - name: Add PHP 7 ppa
    apt_repository: repo='ppa:ondrej/php' state=present

  - name: Install PHP 7 & extensions
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - php7.0
      - php7.0-mysql
      - php7.0-mcrypt
      - php7.0-curl
      - php7.0-mbstring
      - php7.0-dom
      - php7.0-zip
      - php7.0-gd

  - name: Install Mono
    apt: name=mono-complete state=latest update_cache=yes

  - name: Install Supervisor
    apt: name=supervisor state=latest update_cache=yes

  - name: Install Git
    apt: name=git state=latest update_cache=yes

  - name: Install composer
    shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    args:
      creates: /usr/local/bin/composer

  - name: Config php fpm user
    ini_file: dest=/etc/php/7.0/fpm/pool.d/www.conf section=www option=user value=pn mode=0660 backup=yes
    notify: restart fpm

  - name: Config php fpm group
    ini_file: dest=/etc/php/7.0/fpm/pool.d/www.conf section=www option=group value=pn mode=0660 backup=yes
    notify: restart fpm

  - name: Copy public key
    authorized_key: user=pn key="{{ lookup('file', 'conf/worker/key.pub') }}"

  - name: Authorize envoyer to restart fpn
    command: "echo 'pn ALL=NOPASSWD: /usr/sbin/service php7.0-fpm reload' | sudo tee -a /etc/sudoers.d/php-fpm > /dev/null"

  - name: Setup Laravel Scheduler
    cron: >
      job="php /home/pn/parkitectnexus.com/current/artisan schedule:run 1>> /dev/null 2>&1"
      state=present
      user=pn
      name="php artisan schedule:run"

  - name: Setup queues
    template: src=worker/queue dest=/etc/supervisor/conf.d/worker-{{ item }}.conf
    with_items:
      - 1
      - 2
      - 3
      - 4

  handlers:
    - name: restart fpm
      service: name=php7.0-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted