- name: Install Supervisor
  apt: name=supervisor state=latest update_cache=yes

- name: Setup Laravel Scheduler
  cron: >
    job="php /home/pn/parkitectnexus.com/current/artisan schedule:run 1>> /dev/null 2>&1"
    state=present
    user=pn
    name="php artisan schedule:run"

- name: Setup queues
  template: src=conf/worker/queue.conf dest=/etc/supervisor/conf.d/worker-{{ item }}.conf
  with_items:
    - 1
    - 2
    - 3
    - 4